### ISSUE TITLE
Installer has decided to stop working overnight

### ISSUE THREAD

**Issue by chlohe** [PeterTheHe/GoogPress#18]
Tested it at school. Didn't work. Not sure if it's the school computers or something but it needs fixing. It seems to get as far as the URLFetchApp request.

**Comment by stewartmcgown** [comment]
Also need to consider how easy it will be for people to get updates to the code

**Comment by stewartmcgown** [comment]
Installer is working again.

**Comment by PeterTheHe** [comment]
Yeah turned out that the issue was that the school admin had disabled apps
