### ISSUE TITLE
Better way of loading images

### ISSUE THREAD

**Issue by chlohe** [PeterTheHe/GoogPress#27]
We probably need a more efficient way to load images (not base64).

**Comment by stewartmcgown** [comment]
@thomastheforgottenone and I had a good look today for the method to do this. We found that whilst the images are displayed as Google CDN links in public docs like this:

https://lh6.googleusercontent.com/JqcR6CPh97Vt-qkDaBaLJ7qpm3vRSNjDCQoUb2MPDi4FbDnsce0zvLZoKCMZ2QdlrbsXRpy4zOEFV4kwiSo6gpimbCa7yQ9YEUTpSYvrl7p3fXIZPq4wQJmQ5tTKi246AA

There is no way to extract that link from the doc itself.
